version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: retail-inventory-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://15.135.192.6:5000/api
    image: retail-inventory-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
