name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AWS_EC2_IP }}
        username: ubuntu
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          # 1. Project folder par jana (create if not exists)
          if [ ! -d "retail-project" ]; then
            git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} retail-project
          fi
          cd retail-project
          
          # 2. .env file create karna (Secret se)
          echo "${{ secrets.BACKEND_ENV }}" > backend/.env
          
          # 3. Latest code pull karna
          git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
          
          # 3. Docker containers restart karna
          docker compose -f docker-compose.production.yml down
          docker compose -f docker-compose.production.yml up --build -d
          
          # 4. Cleanup old images
          docker image prune -f
